<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>AmberolWpf</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
    <PackageReference Include="Concentus" Version="2.2.2" />
    <PackageReference Include="Concentus.OggFile" Version="1.0.7" />
  </ItemGroup>

</Project>
